version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    expose:
      - '3306'
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp-volume:/var/www
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    ports:
      - '443:443'
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    env_file:
      - .env
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db-volume:
    driver_opts:
      device: ${PWD}/data/db-data
      type: none
      o: bind

  wp-volume:
    driver_opts:
      device: ${PWD}/data/wp-data
      type: none
      o: bind
