version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        SQL_DATABASE: $SQL_DATABASE
        SQL_USER: $SQL_USER
        SQL_PWD: $SQL_PASSWORD
        SQL_ROOT_PWD: $SQL_ROOT_PASSWORD
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    expose:
      - "9000"
    depends_on:
      - mariadb

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $MARIADB_VOLUME_PATH
  
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $WP_VOLUME_PATH


networks:
  inception:
    driver: bridge

